import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import Header from "../components/header";

import "./globals.css";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );  
}



// layout.js
// import { Inter } from "next/font/google";
// import 'react-toastify/dist/ReactToastify.css';
// import Header from "./header/page";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const RootLayout = (props) => {
//   const { children, route } = props;
//   const showHeader = route === '/' || route === '/login';

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {showHeader && <Header />}
//         {children}
//       </body>
//     </html>
//   );
// }

// // Export metadata separately
// export { metadata };
// export default RootLayout;



// RootLayout.jsx

// import { Inter } from "next/font/google";
// import 'react-toastify/dist/ReactToastify.css';
// import Header from "./Header";

// const inter = Inter({ subsets: ["latin"] });

// const RootLayout = (props) => {
//   const { children, route } = props;
//   const showHeader = route === '/' || route === '/login';

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {showHeader && <Header />}
//         {children}
//       </body>
//     </html>
//   );
// };
// export { metadata };

// export default RootLayout;


// Import necessary modules
// 'use client'
// import { Inter } from "next/font/google";
// import 'react-toastify/dist/ReactToastify.css';
// import Header from "./header/page";
// import { useRouter } from "next/navigation"; // Import from next/router

// import "./globals.css";

// // Initialize Inter and metadata
// const inter = Inter({ subsets: ["latin"] });
// const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// // Define the RootLayout component
// const RootLayout = ({ children }) => {
//   const router = useRouter();

//   // List of routes where you want to show the header
//   const routesWithHeader = ['/', '/login'];

//   // Check if the current route is in the list
//   const showHeader = routesWithHeader.includes(router.pathname);

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {showHeader && <Header />} {/* Conditionally render the header */}
//         {children}
//       </body>
//     </html>
//   );
// };

// Export metadata separately
// export { metadata };

// // Export the RootLayout component
// export default RootLayout;

