import { Inter } from "next/font/google";
import 'react-toastify/dist/ReactToastify.css';
import Header from "../components/header";

import "./globals.css";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );  
}